name: Enforce Repo rules

on:
 pull_request:
   branches: [main]
jobs:
  test:
    name: test job
    runs-on: ubuntu-latest 
    steps:
      - name: Dump the github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "${{ env.GITHUB_CONTEXT }}"
      - name: greet user 
        run: |
          echo "Hello world"
